version: '3'
services:
  psql:
    image: postgres:14.7
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: knowthenixkbd-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: knowthenixkbd_tr
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
